import jsPDF from 'jspdf'

/**
 * Format currency in Indian Rupees (INR)
 * Uses standard ASCII 'INR' to guarantee 100% clean rendering in jsPDF without character code distortion.
 */
const formatCurrency = (amount) => {
  return `INR ${(amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

/**
 * Helper to add header banner to PDF report
 */
const renderReportHeader = (doc, title, subtitle) => {
  const pageWidth = doc.internal.pageSize.getWidth()
  
  // Executive Blue Banner Header (#2563EB)
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 32, 'F')

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text(title.toUpperCase(), 15, 18)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(224, 242, 254)
  doc.text(subtitle, 15, 26)

  doc.setFontSize(8)
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, pageWidth - 15, 18, { align: 'right' })
  doc.text('Bilix POS System • Confidential Report', pageWidth - 15, 26, { align: 'right' })
}

/**
 * Render table headers and rows dynamically with proportioned column widths
 */
const renderTable = (doc, startY, columns, rows) => {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  let yPos = startY

  const tableWidth = pageWidth - 2 * margin

  // Calculate Column Widths
  const totalWeight = columns.reduce((sum, col) => sum + (col.width || 10), 0)
  const colWidths = columns.map(col => ((col.width || 10) / totalWeight) * tableWidth)
  const colXs = []
  let currentX = margin
  colWidths.forEach(w => {
    colXs.push(currentX)
    currentX += w
  })

  // Header Row
  doc.setFillColor(37, 99, 235)
  doc.rect(margin, yPos, tableWidth, 9, 'F')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)

  columns.forEach((col, idx) => {
    const x = col.align === 'right' ? colXs[idx] + colWidths[idx] - 3 : colXs[idx] + 3
    doc.text(col.header, x, yPos + 6, { align: col.align || 'left' })
  })

  yPos += 12

  // Table Body Rows
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(30, 41, 59)

  if (rows.length === 0) {
    doc.setFontSize(9)
    doc.text('No record data available for this report period.', margin + 3, yPos + 5)
    return yPos + 12
  }

  rows.forEach((row, rowIndex) => {
    // Page Break check
    if (yPos + 12 > pageHeight - 20) {
      doc.addPage()
      renderReportHeader(doc, 'EXECUTIVE REPORT', 'Page Continued')
      yPos = 40

      // Re-render Header Row on new page
      doc.setFillColor(37, 99, 235)
      doc.rect(margin, yPos, tableWidth, 9, 'F')
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(255, 255, 255)

      columns.forEach((col, idx) => {
        const x = col.align === 'right' ? colXs[idx] + colWidths[idx] - 3 : colXs[idx] + 3
        doc.text(col.header, x, yPos + 6, { align: col.align || 'left' })
      })

      yPos += 12
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(30, 41, 59)
    }

    // Alternating Row Background
    if (rowIndex % 2 === 1) {
      doc.setFillColor(248, 250, 252)
      doc.rect(margin, yPos - 3, tableWidth, 10, 'F')
    }

    doc.setFontSize(8.5)
    columns.forEach((col, colIdx) => {
      let cellVal = row[col.key] !== undefined && row[col.key] !== null ? String(row[col.key]) : ''
      const cellX = col.align === 'right' ? colXs[colIdx] + colWidths[colIdx] - 3 : colXs[colIdx] + 3
      
      const maxColW = colWidths[colIdx] - 6
      if (doc.getTextWidth(cellVal) > maxColW) {
        cellVal = doc.splitTextToSize(cellVal, maxColW)[0] + '...'
      }
      doc.text(cellVal, cellX, yPos + 3, { align: col.align || 'left' })
    })

    yPos += 10
  })

  // Footer line
  doc.setDrawColor(226, 232, 240)
  doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14)
  doc.setFontSize(7)
  doc.setTextColor(148, 163, 184)
  doc.text(`Generated by Bilix POS System • Confidential Operations Report`, pageWidth / 2, pageHeight - 8, { align: 'center' })

  return yPos
}

/**
 * Export Sales PDF Report
 */
export const exportSalesReportPDF = (orders) => {
  const doc = new jsPDF('landscape')
  renderReportHeader(doc, 'Branch Sales Audit Report', 'Itemized list of order transactions')

  const columns = [
    { header: 'Order ID', key: 'id', width: 15 },
    { header: 'Date & Time', key: 'date', width: 32 },
    { header: 'Customer Name', key: 'customer', width: 35 },
    { header: 'Payment Method', key: 'payment', width: 25 },
    { header: 'Status', key: 'status', width: 20 },
    { header: 'Amount', key: 'amount', align: 'right', width: 30 },
  ]

  const rows = orders.map(order => ({
    id: `#${order.id}`,
    date: order.createdAt ? new Date(order.createdAt).toLocaleString('en-IN') : 'N/A',
    customer: typeof order.customer === 'string' ? order.customer : (order.customer?.name || order.customer?.fullName || 'Walk-in Customer'),
    payment: order.paymentType || 'CASH',
    status: order.status || 'COMPLETED',
    amount: formatCurrency(order.totalAmount),
  }))

  renderTable(doc, 40, columns, rows)
  doc.save(`sales_report_${new Date().toISOString().split('T')[0]}.pdf`)
}

/**
 * Export Inventory PDF Report
 */
export const exportInventoryReportPDF = (inventory) => {
  const doc = new jsPDF('landscape')
  renderReportHeader(doc, 'Stock Inventory Audit Report', 'Product quantities and stock valuation breakdown')

  const columns = [
    { header: 'SKU Code', key: 'sku', width: 22 },
    { header: 'Product Name', key: 'name', width: 45 },
    { header: 'Category', key: 'category', width: 25 },
    { header: 'Stock Qty', key: 'quantity', align: 'right', width: 18 },
    { header: 'Unit Price', key: 'price', align: 'right', width: 25 },
    { header: 'Stock Value', key: 'totalValue', align: 'right', width: 28 },
  ]

  const rows = inventory.map(item => ({
    sku: item.product?.sku || 'SKU-N/A',
    name: item.product?.name || 'Inventory Item',
    category: item.product?.category?.name || 'General',
    quantity: item.quantity || 0,
    price: formatCurrency(item.product?.sellingPrice),
    totalValue: formatCurrency((item.quantity || 0) * (item.product?.sellingPrice || 0)),
  }))

  renderTable(doc, 40, columns, rows)
  doc.save(`inventory_report_${new Date().toISOString().split('T')[0]}.pdf`)
}

/**
 * Export Staff Performance PDF Report
 */
export const exportStaffReportPDF = (employees, orders) => {
  const doc = new jsPDF('landscape')
  renderReportHeader(doc, 'Staff & Cashier Directory Report', 'Active employee roster and shift records')

  const columns = [
    { header: 'Staff ID', key: 'id', width: 15 },
    { header: 'Full Name', key: 'name', width: 35 },
    { header: 'Email Address', key: 'email', width: 45 },
    { header: 'Role', key: 'role', width: 25 },
    { header: 'Phone Number', key: 'phone', width: 25 },
    { header: 'Branch', key: 'branch', width: 25 },
  ]

  const rows = employees.map(emp => ({
    id: `#${emp.id}`,
    name: emp.fullName || 'Employee',
    email: emp.email || 'N/A',
    role: emp.role ? emp.role.replace('ROLE_', '').replace('_', ' ') : 'STAFF',
    phone: emp.phone || 'N/A',
    branch: emp.branch?.name || 'Main Branch',
  }))

  renderTable(doc, 40, columns, rows)
  doc.save(`staff_report_${new Date().toISOString().split('T')[0]}.pdf`)
}

/**
 * Export Customer PDF Report
 */
export const exportCustomerReportPDF = (customers) => {
  const doc = new jsPDF('landscape')
  renderReportHeader(doc, 'Branch Customer Directory Report', 'Registered customer roster and total spend')

  const columns = [
    { header: 'Cust ID', key: 'id', width: 15 },
    { header: 'Customer Name', key: 'name', width: 35 },
    { header: 'Email Address', key: 'email', width: 45 },
    { header: 'Phone Number', key: 'phone', width: 25 },
    { header: 'Orders Count', key: 'orders', align: 'right', width: 20 },
    { header: 'Total Lifetime Spend', key: 'spent', align: 'right', width: 30 },
  ]

  const rows = customers.map(cust => ({
    id: `#${cust.id}`,
    name: cust.name || cust.fullName || 'Customer',
    email: cust.email || 'N/A',
    phone: cust.phone || 'N/A',
    orders: cust.orderCount || 0,
    spent: formatCurrency(cust.totalSpent),
  }))

  renderTable(doc, 40, columns, rows)
  doc.save(`customer_report_${new Date().toISOString().split('T')[0]}.pdf`)
}

/**
 * Export Refunds PDF Report
 */
export const exportRefundsReportPDF = (refunds) => {
  const doc = new jsPDF('landscape')
  renderReportHeader(doc, 'Refund Transactions Audit Report', 'Log of processed branch order refunds')

  const columns = [
    { header: 'Refund ID', key: 'id', width: 20 },
    { header: 'Order Ref', key: 'orderId', width: 20 },
    { header: 'Return Reason', key: 'reason', width: 60 },
    { header: 'Refund Date & Time', key: 'date', width: 35 },
    { header: 'Refund Amount', key: 'amount', align: 'right', width: 30 },
  ]

  const rows = refunds.map(r => ({
    id: `#${r.id}`,
    orderId: `#${r.order?.id || r.orderId || 'N/A'}`,
    reason: r.reason || 'Customer Return',
    date: r.createdAt ? new Date(r.createdAt).toLocaleString('en-IN') : 'N/A',
    amount: formatCurrency(r.amount),
  }))

  renderTable(doc, 40, columns, rows)
  doc.save(`refunds_report_${new Date().toISOString().split('T')[0]}.pdf`)
}

/**
 * Export Complete Multi-Page Shift Summary PDF Report
 */
export const exportShiftSummaryReportPDF = (shiftData) => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  let yPos = margin

  const cashierName = shiftData?.cashier?.fullName || shiftData?.cashier?.email || 'Cashier'
  const startTime = shiftData?.shiftStart ? new Date(shiftData.shiftStart).toLocaleString('en-IN') : 'N/A'
  const endTime = shiftData?.shiftEnd ? new Date(shiftData.shiftEnd).toLocaleString('en-IN') : 'Shift Active'

  // Header Banner
  renderReportHeader(doc, 'Cashier Shift Summary Report', `Cashier: ${cashierName} • Started: ${startTime}`)

  yPos = 42

  // Shift Meta Box
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 24, 2, 2, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 24, 2, 2, 'S')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text('SHIFT OVERVIEW', margin + 5, yPos + 6)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text(`Cashier Name: ${cashierName}`, margin + 5, yPos + 13)
  doc.text(`Shift Start: ${startTime}`, margin + 5, yPos + 19)

  doc.text(`Status: ${shiftData?.shiftEnd ? 'Completed' : 'ACTIVE'}`, pageWidth / 2 + 10, yPos + 13)
  doc.text(`Shift End: ${endTime}`, pageWidth / 2 + 10, yPos + 19)

  yPos += 30

  // KPI Summary Table
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text('1. FINANCIAL PERFORMANCE SUMMARY', margin, yPos)
  yPos += 5

  const kpiColumns = [
    { header: 'Metric', key: 'metric', width: 50 },
    { header: 'Orders Count', key: 'orders', width: 25 },
    { header: 'Amount', key: 'amount', align: 'right', width: 25 },
  ]

  const kpiRows = [
    { metric: 'Gross Sales Revenue', orders: shiftData?.totalOrders || 0, amount: formatCurrency(shiftData?.totalSales) },
    { metric: 'Total Refund Deductions', orders: shiftData?.refunds?.length || 0, amount: `- ${formatCurrency(shiftData?.totalRefunds)}` },
    { metric: 'Net Register Revenue', orders: shiftData?.totalOrders || 0, amount: formatCurrency(shiftData?.netSale) },
  ]

  yPos = renderTable(doc, yPos, kpiColumns, kpiRows)
  yPos += 10

  // Payment Breakdown
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text('2. PAYMENT METHODS BREAKDOWN', margin, yPos)
  yPos += 5

  const payColumns = [
    { header: 'Payment Method', key: 'method', width: 40 },
    { header: 'Transaction Count', key: 'count', width: 30 },
    { header: 'Share (%)', key: 'share', width: 30 },
    { header: 'Total Collected', key: 'total', align: 'right', width: 40 },
  ]

  const paySummaries = shiftData?.paymentSummaries || []
  const payRows = paySummaries.map(p => ({
    method: p.type || 'CASH',
    count: p.transactionCount || 0,
    share: `${(p.percentage || 0).toFixed(1)}%`,
    total: formatCurrency(p.totalAmount),
  }))

  yPos = renderTable(doc, yPos, payColumns, payRows.length > 0 ? payRows : [{ method: 'Cash', count: shiftData?.totalOrders || 0, share: '100%', total: formatCurrency(shiftData?.totalSales) }])
  yPos += 10

  // Top Selling Items
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text('3. TOP SELLING PRODUCTS', margin, yPos)
  yPos += 5

  const topColumns = [
    { header: 'Product Name', key: 'name', width: 60 },
    { header: 'Qty Sold', key: 'qty', width: 25 },
    { header: 'Unit Price', key: 'price', align: 'right', width: 30 },
    { header: 'Total Revenue', key: 'total', align: 'right', width: 35 },
  ]

  const topProducts = shiftData?.topSellingProducts || []
  const topRows = topProducts.map(p => ({
    name: p.name || 'Product',
    qty: p.quantity || 1,
    price: formatCurrency(p.sellingPrice),
    total: formatCurrency((p.quantity || 1) * (p.sellingPrice || 0)),
  }))

  renderTable(doc, yPos, topColumns, topRows)

  doc.save(`shift_summary_${cashierName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`)
}

